version: '3.3'
services:
    db:
        image: postgres:14-alpine
        ports:
            - 5432:5432
        volumes:
            - ./data:/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_PASSWORD=admin
            - POSTGRES_USER=admin
            - POSTGRES_DB=simpleexpense
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U admin -d simpleexpense" ]
            interval: 5s
            timeout: 5s
            retries: 5

    client:
        build: client
        ports:
            - "8080:8080"

    backend:
        build: backend
        ports:
            - "3001:3001"
        depends_on:
            db:
                condition: service_healthy
        links:
            - db:database

