version: '3.3'
services:
    db:
        image: postgres:14-alpine
        ports:
            - "5432:5432"
        volumes:
            - ./data:/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_PASSWORD=admin
            - POSTGRES_USER=admin
            - POSTGRES_DB=simpleexpense
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U admin -d simpleexpense" ]
            interval: 5s
            timeout: 5s
            retries: 5

    client:
        build: client
        environment:
            - BACKEND_HOST=backend
            - BACKEND_PORT=3001
        ports:
            - "8080:8080"
        links:
            - backend:backend

    backend:
        build: backend
        ports:
            - "3001:3001"
        environment:
            - DB_PORT=5432
            - DB_HOST=database
            - DB_USER=admin
            - DB_PASSWORD=admin
            - DB_DATABASE=simpleexpense
        depends_on:
            db:
                condition: service_healthy
        links:
            - db:database

