version: '3.3'
services:
    db:
        image: postgres:14-alpine
        ports:
            - "5432:5432"
        volumes:
            - ./data:/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_PASSWORD=admin
            - POSTGRES_USER=admin
            - POSTGRES_DB=simpleexpense
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U admin -d simpleexpense" ]
            interval: 5s
            timeout: 5s
            retries: 5

    client:
        build: client
        environment:
            - VITE_BACKEND_HOST=http://backend
            - VITE_BACKEND_PORT=3001
        links:
            - backend

    backend:
        build: backend
        environment:
            - DB_PORT=5432
            - DB_HOST=database
            - DB_USER=admin
            - DB_PASSWORD=admin
            - DB_DATABASE=simpleexpense
        depends_on:
            db:
                condition: service_healthy
        links:
            - db:database

    proxy:
        image: nginx:latest
        ports:
            - "3000:3000"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - backend
            - client